# -*- coding: utf-8 -*-
"""list_operation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18_NuvkSmiBHMBiaRtCv59mmcVNPhMO9f
"""

# Create an empty list
my_list = []

# Append elements
my_list.append(10)
my_list.append(20)
my_list.append(30)
my_list.append(40)

# Insert value 15 at the second position (index 1)
my_list.insert(1, 15)

# Extend list with another list
my_list.extend([50, 60, 70])

# Remove the last element
my_list.pop()

# Sort list in ascending order
my_list.sort()

# Find and print the index of value 30
index_of_30 = my_list.index(30)
print("Index of 30:", index_of_30)

# Print final list for verification
print("Final list:", my_list)